export const GetterTypes = {
  AVALIABLE_ADD_ASSETS: "AVALIABLE_ADD_ASSETS",
  GET_IS_LIQUIDITY_ADDED: "GET_IS_LIQUIDITY_ADDED",
  ACCOUNT_PAIRS: "ACCOUNT_PAIRS",
  GET_ACCOUNT_PAIR: "GET_ACCOUNT_PAIR",
  ACCOUNT_OVERVIEW: "ACCOUNT_OVERVIEW",
};
