export const prefix = "pool/";

export const MutationTypes = {
  PUT_CACHE: "PUT_CACHE",
  SET_ASSETS: "SET_ASSETS",
  SET_PAIRS: "SET_PAIRS",
  SET_ASSETS_WHITE_LISTS: "SET_ASSETS_WHITE_LISTS",
  SET_FIATS: "SET_FIATS",
  SET_MULTISIG_ASSETS: "SET_MULTISIG_ASSETS",
  SET_POOL_LOADING: "SET_POOL_LOADING",
};

export const ActionTypes = {
  LOAD_POOL_ASSETS: "LOAD_POOL_ASSETS",
  LOAD_FIATS: "LOAD_FIATS",
  LOAD_POOL_PAIRS: "LOAD_PAIRS",
  LOAD_MULTISIG_ASSETS: "LOAD_MULTISIG_ASSETS",
  LOAD_POOL_DATA: "LOAD_POOL_DATA",
};

export const GetterTypes = {
  POOL_OVERVIEW: "POOL_OVERVIEW",
  AVALIABLE_ASSETS: "AVALIABLE_ASSETS",
  AVALIABLE_PAIRS: "AVALIABLE_PAIRS",
  AVALIABLE_SWAP_ASSETS: "AVALIABLE_SWAP_ASSETS",
  GET_ASSET_BY_ID: "GET_ASSET_BY_ID",
  GET_ASSET_BY_SYMBOL: "GET_ASSET_BY_SYMBOL",
  GET_PAIR_BY_IDS: "GET_PAIR_BY_IDS",
  GET_PAIRS_BY_ASSET: "GET_PAIRS_BY_ASSET",
  GET_PAIR_BY_LIQUIDIY_ID: "GET_PAIR_BY_LIQUIDIY_ID",
  AVALIABLE_ASSETS_META: "AVALIABLE_ASSETS_META",
};
