export const prefix = "account/";

export const GetterTypes = {
  USER_ID: "USER_ID",
  GET_BALANCE_BY_ID: "GET_BALANCE_BY_ID",
};

export const MutationTypes = {
  SET_PROFILE: "SET_PROFILE",
  SET_WALLET_ASSET: "SET_WALLET_ASSET",
  SET_WALLET_ASSETS: "SET_WALLET_ASSETS",
  CLEAR_ACCOUNT: "CLEAR_ACCOUNT",
};

export const ActionTypes = {
  LOAD_PROFILE: "LOAD_PROFILE",
  LOAD_WALLET_ASSETS: "LOAD_WALLET_ASSETS",
  LOAD_WALLET_ASSET: "LOAD_WALLET_ASSET",
};
