export const prefix = "account/";

export const GetterTypes = {
  USER_ID: "USER_ID",
  GET_BALANCE_BY_ID: "GET_BALANCE_BY_ID",
  GET_PROFIT_BY_PAIR: "GET_PROFIT_BY_PAIR",
  GET_WALLET_BALANCE: "GET_WALLET_BALANCE",
};

export const MutationTypes = {
  SET_PROFILE: "SET_PROFILE",
  SET_WALLET_ASSET: "SET_WALLET_ASSET",
  SET_WALLET_ASSETS: "SET_WALLET_ASSETS",
  CLEAR_ACCOUNT: "CLEAR_ACCOUNT",
  SET_PROFIT: "SET_PROFIT",
};

export const ActionTypes = {
  LOAD_PROFILE: "LOAD_PROFILE",
  LOAD_PROFIT: "LOAD_PROFITS",
  LOAD_WALLET_ASSETS: "LOAD_WALLET_ASSETS",
  LOAD_WALLET_ASSET: "LOAD_WALLET_ASSET",
};
