export const prefix = "app/";

export const MutationTypes = {
  SET_PAYING: "SET_PAYING",
  SET_SETTINGS: "SET_SETTINGS",
  SET_APPBAR: "SET_APPBAR",
  SET_APP_INFO: "SET_APP_INFO",
  SET_APP_INITING: "SET_APP_INITING",
  SET_BOTTOM_NAV: "SET_BOTTOM_NAV",
  SET_CONTENT_CLASS: "SET_CONTENT_CLASS",
  SET_CONTENT_STYLE: "SET_CONTENT_STYLE",
};

export const ActionTypes = {
  LOAD_APP_INFO: "LOAD_APP_INFO",
};
