const data = {
  BTC: {
    name: "Bitcoin",
    explorer: "https://www.blockchain.com/explorer",
    intro: {
      en: [
        `Bitcoin is a decentralized cryptocurrency originally described in a 2008 whitepaper by a person, or group of people, using the alias Satoshi Nakamoto. It was launched soon after, in January 2009.`,
        `Bitcoin is a peer-to-peer online currency, meaning that all transactions happen directly between equal, independent network participants, without the need for any intermediary to permit or facilitate them. Bitcoin was created, according to Nakamoto’s own words, to allow “online payments to be sent directly from one party to another without going through a financial institution.”`,
        `Some concepts for a similar type of a decentralized electronic currency precede BTC, but Bitcoin holds the distinction of being the first-ever cryptocurrency to come into actual use.`,
      ],
      zh: [
        `比特币是一种完全去中心化的数字货币。与美元不同，您无法将它拿在手上，也不能把它存进银行。比特币运行在一个点对点的网络上，人们可以在无需中介机构（如银行、央行或者支付机构）的情况下发送和接收比特币。事实上，没有任何一家中心化机构或者支付系统可以控制比特币。`,
        `目前，CMC官网上列出的加密货币达到了6千多种，但比特币才是有史以来第一个加密货币。2008年10月31日，有人（或者一群人）以“中本聪”的名义发表了著名的比特币白皮书。`,
        `白皮书的第一行写道：“一个真正的的点对点的电子现金应该允许从发起方直接在线支付给对方，而不需要通过第三方的金融服务机构。”`,
        `比特币网络于2009年1月日正式发布，这标志着加密货币革命的开始。`,
      ],
    },
    website: "https://bitcoin.org",
    issue: "2008/10/31",
    total: "21000000",
    circulation: "18247575",
  },
  ETH: {
    name: "Ethereum",
    explorer: "https://etherscan.io/",
    intro: {
      en: [
        `Ethereum is a decentralized open-source blockchain system that features its own cryptocurrency, Ether. ETH works as a platform for numerous other cryptocurrencies, as well as for the execution of decentralized smart contracts.`,
        `Ethereum was first described in a 2013 whitepaper by Vitalik Buterin. Buterin, along with other co-founders, secured funding for the project in an online public crowd sale in the summer of 2014 and officially launched the blockchain on July 30, 2015.`,
        `Ethereum’s own purported goal is to become a global platform for decentralized applications, allowing users from all over the world to write and run software that is resistant to censorship, downtime and fraud.`,
      ],
      zh: [
        `以太坊是一个智能合约平台，开发人员可以在以太坊区块链上构建去中心化应用(DApps)。以太币是以太坊平台的本地数字货币。`,
        `以太坊的资金部分来源于以太坊基金会，该基金会是以太坊生态下的一个非营利组织。以太坊生态还包括诸多联合企业，如以太坊企业联盟等。`,
      ],
    },
    website: "https://www.ethereum.org/",
    issue: "2014/7/24",
    total: "109542949",
    circulation: "109542949",
  },
  XIN: {
    name: "Mixin",
    explorer: "https://mixin.one/snapshots",
    intro: {
      en: [
        `Mixin (XIN) is a smart-contract network designed to facilitate peer-to-peer (P2P) transactions with digital assets across blockchains.  Leveraging Directed Acyclic Graph (DAG) and Byzantine Fault-Tolerant protocols, Mixin aspires to help other blockchains achieve trillions of TPS, sub-second final confirmations, zero transaction fees, enhanced privacy, and unlimited extensibility. Mixin Messenger, the first dApp created on Mixin Network, combines Facebook Messenger-like features with a multi-currency mobile wallet. XIN is the native cryptocurrency of the Mixin Network, which also supports BTC, ETH, BCH, ETC, and more.`,
        `The Mixin Kernel  now supports 24 blockchains, over 50,000 cryptocurrencies, and all manners of bots.`,
      ],
      zh: [
        `XIN是Mixin平台的唯一代币，总量恒定为1,000,000。Mixin 是一个免费、快速的点对点跨链数字资产交易网络，可帮助其他区块链分布式账本获得超高TPS、亚秒级确认、零手续费、加强隐私、无限扩展的能力。Mixin网络使用PoS + Asynchronous BFT 共识机制，DAG数据储存，通过带惩罚机制的 PoS 去中心化网络，TEE 硬件加固，数万轻节点监督全节点防止作恶。`,
      ],
    },
    website: "https://mixin.one",
    issue: "2017/11/25",
    total: "1000000",
    circulation: "537721",
  },
  MOB: {
    name: "MobileCoin",
    explorer: "",
    intro: {
      en: [
        `MobileCoin is a privacy-preserving payments network designed for use on mobile devices.`,
      ],
      zh: [
        `MobileCoin 是一个隐私支付协议，专注于为移动通讯应用程序提供安全、隐私、极简的加密货币钱包服务，有望接入月活跃用户超过 4 千万的 Signal。`,
      ],
    },
    website: "https://www.mobilecoin.com/",
    issue: "2020/12/7",
    total: "250000000",
    circulation: "",
  },
  pUSD: {
    name: "Pando USD",
    explorer: "",
    intro: {
      en: [
        `Named after Pando tree, the oldest and heaviest known living  organism that has massive underground root system, Pando USD is the stablecoin on Mixin Network. Soft-pegged to US dollar, it is currently generated by collateralizing BTC and ETH at the collateral rate over 200%. `,
      ],
      zh: [
        `pUSD命名来源与Pando树，这是地球上年纪最大的生物，地表上看上去像一片树林，其实它仅为一棵树，地底下面的根是连着的。Pando是Mixin网络上用BTC、ETH等去中心化货币抵押铸出来的绑定美元的稳定币，抵押率超过200%。`,
      ],
    },
    website: "https://pando.im/",
    issue: "2020/12/25",
    total: "",
    circulation: "",
  },
  "USDT-ERC20": {
    name: "Tether",
    explorer:
      "https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7",
    intro: {
      en: [
        `USDT is a stablecoin (stable-value cryptocurrency) that mirrors the price of the U.S. dollar, issued by a Hong Kong-based company Tether. The token’s peg to the USD is achieved via maintaining a sum of dollars in reserves that is equal to the number of USDT in circulation.`,
        `Originally launched in July 2014 as Realcoin, a second-layer cryptocurrency token built on top of Bitcoin’s blockchain through the use of the Omni platform, it was later renamed to USTether, and then, finally, to USDT. In addition to Bitcoin’s, USDT was later updated to work on the Ethereum, EOS, Tron, Algorand, and OMG blockchains.`,
        `The stated purpose of USDT is to combine the unrestricted nature of cryptocurrencies — which can be sent between users without a trusted third-party intermediary — with the stable value of the US dollar.`,
      ],
      zh: [
        `泰达币(USDT)是一种数字货币，其价值意在反映美元的价值。 泰达币于2014年推出，其目的是创建一种稳定的加密货币，可像数字美元或“稳定币”一样使用。泰达币的价格与美元锚定。`,
        `泰达币最开始使用比特币网络的Omni层作为其传输协议，现在它可以在以太坊上作为ERC-20代币使用。泰达币已经在比特币(Omni和Liquid协议)、以太坊、EOS、波场区块链上发行。`,
        `泰达币由Tether Limited发行，这家公司与加密货币交易所Bitfinex拥有同一个CEO。Tether曾声称为泰达币储备了100%的美元准备金。2019年，该公司的律师表示只有74%的泰达币有准备金做支撑。对此Tether的解释是，其子公司的贷款也属于储备金的一部分。`,
      ],
    },
    website: "https://tether.to/",
    issue: "2017/09",
    total: "39920510120",
    circulation: "39920510120",
  },
  "USDT-TRC20": {
    name: "Tether",
    explorer:
      "https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    intro: {
      en: [
        `USDT is a stablecoin (stable-value cryptocurrency) that mirrors the price of the U.S. dollar, issued by a Hong Kong-based company Tether. The token’s peg to the USD is achieved via maintaining a sum of dollars in reserves that is equal to the number of USDT in circulation.`,
        `Originally launched in July 2014 as Realcoin, a second-layer cryptocurrency token built on top of Bitcoin’s blockchain through the use of the Omni platform, it was later renamed to USTether, and then, finally, to USDT. In addition to Bitcoin’s, USDT was later updated to work on the Ethereum, EOS, Tron, Algorand, and OMG blockchains.`,
        `The stated purpose of USDT is to combine the unrestricted nature of cryptocurrencies — which can be sent between users without a trusted third-party intermediary — with the stable value of the US dollar.`,
      ],
      zh: [
        `泰达币(USDT)是一种数字货币，其价值意在反映美元的价值。 泰达币于2014年推出，其目的是创建一种稳定的加密货币，可像数字美元或“稳定币”一样使用。泰达币的价格与美元锚定。`,
        `泰达币最开始使用比特币网络的Omni层作为其传输协议，现在它可以在以太坊上作为ERC-20代币使用。泰达币已经在比特币(Omni和Liquid协议)、以太坊、EOS、波场区块链上发行。`,
        `泰达币由Tether Limited发行，这家公司与加密货币交易所Bitfinex拥有同一个CEO。Tether曾声称为泰达币储备了100%的美元准备金。2019年，该公司的律师表示只有74%的泰达币有准备金做支撑。对此Tether的解释是，其子公司的贷款也属于储备金的一部分。`,
      ],
    },
    website: "https://tether.to/",
    issue: "2019/4/16",
    total: "17794331935.065677",
    circulation: "17794331935.065677",
  },
  EOS: {
    name: "EOS",
    explorer: "https://eosauthority.com/",
    intro: {
      en: [
        `EOS is a platform that’s designed to allow developers to build decentralized apps (otherwise known as DApps for short.)`,
        `The project’s goal is relatively simple: to make it as straightforward as possible for programmers to embrace blockchain technology — and ensure that the network is easier to use than rivals. As a result, tools and a range of educational resources are provided to support developers who want to build functional apps quickly.`,
        `Other priorities include delivering greater levels of scalability than other blockchains, some of which can only handle less than a dozen transactions per second.`,
        `EOS also aims to improve the experience for users and businesses. While the project tries to deliver greater security and less friction for consumers, it also vies to unlock flexibility and compliance for enterprises.`,
      ],
      zh: [
        `EOSIO 区块链是一个去中心化系统，由其本地货币柚子（EOS）提供支持，该平台还支持去中心化应用(DApp)。柚子通常用于商业用途，可以作为 DApp 筹集资金的筹码。2017年5月，block.one 发布了柚子，它不代表任何特定的事物，因为创建它的人也从未正式定义它。block.one 的 CTO 是 Dan Laimer，他曾创立了 Bitshares 和 Steem。`,
        `柚子在2017年进行了为期一年的 ICO，在五天内共发行了2亿枚代币（占总量的20%），其余7亿枚（70%）在接下来的一年中继续进行分配，1亿枚（10%）托管在 block.one 中。`,
        `柚子协议的运作方式类似于谷歌商店和苹果商店，它模拟了真实计算机的大部分属性，包括一些硬件计算资源（如用于数据处理的CPU和你GPU，本地/RAM内存以及硬盘储存），这些资源会平均分配给柚子加密货币的持有者。另外，柚子还支持用于界面开发的Web工具包。`,
        `本质上，EOSIO作为智能合约平台和分布式操作系统运行，它旨在通过去中心化自治公司模型来部署工业化规模的DApp。该智能合约平台声称每秒可以处理数百万笔交易，而且不需要手续费。柚子系统是一种引入了区块链架构的软件，其目标是增加去中心化应用的扩展性。柚子软件系统提供帐户，身份验证，数据库，异步通信以及跨多个CPU内核或群集的应用程序调度。`,
      ],
    },
    website: "https://eos.io/",
    issue: "2018/6/1",
    total: "1028098256",
    circulation: "951597844",
  },
  BOX: {
    name: "BOX",
    explorer: "",
    intro: {
      en: [
        `Box is a crytocurrency ETF fund containing seven underlying assets: BTC, ETH, EOS, MOB, XIN, UNI and DOT, designed by Xiaolai Li. Box Tokens represents the shares of the fund. `,
      ],
      zh: [
        `BOX 是一个完全公开、透明的基金产品，由李笑来设计。`,
        `BOX 的成分由 7 个标的构成，它们分别是 BTC、ETH、EOS、DOT、MOB、XIN、UNI。`,
        `BOX Token 是参与 BOX 投资的权益证明，它是一个 ERC20 Token。`,
      ],
    },
    website: "https://b.watch/",
    issue: "2019/7/3",
    total: "",
    circulation: "",
  },
  ONE: {
    name: "BigONE Token",
    explorer:
      "https://etherscan.io/token/0x946551dd05c5abd7cc808927480225ce36d8c475",
    intro: {
      en: [
        `BigONE Token (ONE) is a token based on the ERC20 contract issued by the BigONE trading platform. ONE holders stand to enjoy benefits on the BigONE trading platform.`,
      ],
      zh: [],
    },
    website: "https://big.one/",
    issue: "2018/6/25",
    total: "12689446978",
    circulation: "9449081034",
  },
  USDC: {
    name: "USD Coin",
    explorer:
      "https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    intro: {
      en: [
        `USD Coin (known by its ticker USDC) is a stablecoin that is pegged to the U.S. dollar on a 1:1 basis. Every unit of this cryptocurrency in circulation is backed up by $1 that is held in reserve, in a mix of cash and short-term U.S. Treasury bonds. The Centre consortium, which is behind this asset, says USDC is issued by regulated financial institutions.`,
        `The stablecoin originally launched on a limited basis in September 2018. Put simply, USD Coin’s mantra is “digital money for the digital age” — and the stablecoin is designed for a world where cashless transactions are becoming more common.`,
        `Several use cases have been unveiled for the USD Coin. As well as providing a safe haven for crypto traders in times of volatility, those behind the stablecoin say it can also allow businesses to accept payments in digital assets, and shake up an array of sectors including decentralized finance and gaming.`,
        `Overall, the goal is to create an ecosystem where USDC is accepted by as many wallets, exchanges, service providers and dApps as possible.`,
      ],
      zh: [
        `USD Coin（USDC）是一种由美元完全支持并由Centre Consortium开发的稳定币。Centre可以发行并兑换USDC且无需任何额外费用，并获取了在美国作为货币转账机构并在欧洲作为电子货币机构的许可。 始终可将USDC与美元进行1:1兑换。（抵押品的）资金存放于独立的、由第三方监测并审计的银行账户中。 USD Coin已经成为规模最大的稳定币之一（供应量将近5亿），其支持范围已经扩展到多个去中心化应用程序和诸多交易平台。`,
      ],
    },
    website: "https://www.centre.io/usdc",
    issue: "2019/9/18",
    total: "10311734323",
    circulation: "10105778463",
  },
  PRS: {
    name: "PressOne",
    explorer: "https://press.one/blockchain/main",
    intro: {
      en: [`Blockchain-based digital content trading and distribution network`],
      zh: [
        `Press.One是一个基于EOS区块链基础设施的内容分发公链， 人们可以在这里创建各种各样基于内容的去中心化应用。`,
      ],
    },
    website: "https://press.one",
    issue: "2018/1/8",
    total: "2000000000",
    circulation: "284742628",
  },
  DAI: {
    name: "Dai",
    explorer:
      "https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f",
    intro: {
      en: [
        `DAI is an Ethereum-based stablecoin (stable-price cryptocurrency) whose issuance and development is managed by the Maker Protocol and the MakerDAO decentralized autonomous organization.`,
        `The price of DAI is soft-pegged to the U.S. dollar and is collateralized by a mix of other cryptocurrencies that are deposited into smart-contract vaults every time new DAI is minted.`,
        `It is important to differentiate between Multi-Collateral DAI and Single-Collateral DAI (SAI), an earlier version of the token that could only be collateralized by a single cryptocurrency; SAI also doesn’t support the DAI Savings Rate, which allows users to earn savings by holding DAI tokens.`,
        `Multi-Collateral DAI was launched in November 2019.`,
      ],
      zh: [
        `DAI是一个按照市场机制稳定的一个以太坊数字代表，来自 MakerDAO项目。Maker是以太坊上最早的去中心化自治组织之一（DAO）和智能合约系统，Maker 平台提供稳定基础货币DAIDAI是有数字资产抵押担保的基础货币，和美元保持 1:1 的锚定。`,
      ],
    },
    website: "https://makerdao.com",
    issue: "",
    total: "2937409489",
    circulation: "2937409463",
  },
  IQ: {
    name: "Everipedia",
    explorer: "https://bloks.io/account/everipediaiq",
    intro: {
      en: [
        `Everipedia+PredIQt is a decentralized knowledge base and DeFi platform that includes a prediction market, money market, and synthetic asset system. The IQ token powers all applications and is used for governance of the system.`,
      ],
      zh: [
        `IQ是IQ网络的基础，这是一个建立在EOS基础上的区块链协议，能够为以知识为核心的去中心化应用提供助力。IQ网络的旗舰DApp是Everipedia，它是一个更现代，更包容的百科全书式的新一代知识库。2015年它是维基百科的替代品，2018年过渡到区块链领域。用户持有IQ并在平台编辑文章，积极的贡献将会获得奖励。此外，作为一个去中心化的平台，Everipedia上的内容是不可更改的，用户可以从世界上任何地方（包括维基百科被封锁的国家）进行访问。IQ网络另一个DApp去中心化的市场预测产品：PredIQt，于2019年第三季度推出。`,
      ],
    },
    website: "https://everipedia.org/",
    issue: "2018/8/9",
    total: "10017820877",
    circulation: "9994522659",
  },
  XMR: {
    name: "Monero",
    explorer: "https://localmonero.co/blocks",
    intro: {
      en: [
        `Monero was launched in 2014, and its goal is simple: to allow transactions to take place privately and with anonymity. Even though it’s commonly thought that BTC can conceal a person’s identity, it’s often easy to trace payments back to their original source because blockchains are transparent. On the other hand, XMR is designed to obscure senders and recipients alike through the use of advanced cryptography.`,
        `The team behind Monero say privacy and security are their biggest priorities, with ease of use and efficiency coming second. It aims to provide protection to all users — irrespective of how technologically competent they are.`,
        `Overall, XMR aims to allow payments to be made quickly and inexpensively without fear of censorship.`,
      ],
      zh: [
        `门罗币(XMR)是一种私有、安全且不可追溯的加密货币，2014年4月18日作为ByteCoin的分叉币推出。它是一种开源的、以隐私为导向的数字货币，构建在不透明的区块链网络上。门罗币开发人保护员宣称，用户可以完全控制自己的资金和隐私，因为没有人可以看到别人的账户余额或者交易记录。`,
        `作为主打隐私的加密货币，门罗币采用了环形签名和隐身地址。环形签名是一种保护匿名数字签名，它不会暴露交易签名的主人。环形签名由发送方的公钥与区块链上的其他公钥混合生成。隐身地址则是在每次交易期间随机生成的一次性地址，用于隐藏交易的目标地址和接受者的身份。环形机密交易(RingCT)还能隐藏交易金额；2017年，这一特性被添加到门罗币网络上，成为交易网络的强制功能。`,
        `门罗币基于CryptoNote协议，与比特币不同，它具有动态的区块大小和交易费用。`,
      ],
    },
    website: "https://www.getmonero.org/",
    issue: "2014/04",
    total: "17870887",
    circulation: "17870887",
  },
  UNI: {
    name: "Uniswap",
    explorer:
      "https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    intro: {
      en: [
        `Uniswap is a popular decentralized trading protocol, known for its role in facilitating automated trading of decentralized finance (DeFi) tokens.`,
        `An example of an automated market maker (AMM), Uniswap launched in November 2018, but has gained considerable popularity thanks to the DeFi phenomenon and associated surge in token trading.`,
        `Uniswap aims to keep token trading automated and completely open to anyone who holds tokens, while improving the efficiency of trading versus that on traditional exchanges.`,
        `Uniswap creates more efficiency by solving liquidity issues with automated solutions, avoiding the problems which plagued the first decentralized exchanges.`,
        `In September 2020, Uniswap went a step further by creating and awarding its own governance token, UNI, to past users of the protocol. This added both profitability potential and the ability for users to shape its future — an attractive aspect of decentralized entities.`,
      ],
      zh: [
        `Uniswap是基于以太坊区块链构建的去中心化交易协议，可提供ERC-20代币的非托管交易。它的第一个版本(Uniswap v1)自2018年11月开始运行(在DevCon 4上发布)，而第二个版本(Uniswap v2)于2020年5月发布。`,
        `在Uniswap中，用户可以交换代币，将代币添加到池中以赚取费用或添加代币交易对，而无需信任任何中央中介。由于所有交互都是直接在链上进行的，因此要花费交易手续费，Uniswap已成为以太坊公共网络上最重要的手续费提供者，并成为使用最广泛的分布式应用程序。 Uniswap建立在称为自动做市商(AMM)的独特系统上。其核心是由两个ERC-20代币组成的池来创建流动性。作为对流动性条款的奖励，当事方(流动性提供者或LP)收取每当个人交换代币时产生的交换费。在Uniswap v2中，交换费用设置为名义交易量的0.30％。收取的费用分配到池的储备金中。开启协议开关后，UNI持有者将收取每次交易手续费的0.05％，而流动性提供者的奖励将降低至0.25％。`,
        `尽管不是首个AMM，Uniswap仍在普及自动化做市商协议，从而催生了诸如SushiSwap之类依靠其经过审计的开源代码的竞争协议。`,
        ` UNI是以太坊区块链上的ERC-20治理代币，代币持有者对Uniswap协议治理，UNI代币社区资金，协议费用转换的控制(如果激活，则0.05％的费用将由UNI代币持有者收取)，eth ENS，Uniswap默认代币列表(tokens.uniswap.eth)和SOCKS流动性代币等做出决断。`,
      ],
    },
    website: "https://uniswap.org/",
    issue: "",
    total: "1000000000",
    circulation: "120557355",
  },
  DOT: {
    name: "Polkadot",
    explorer: "https://polkascan.io/",
    intro: {
      en: [
        `Polkadot is an open-source sharding multichain protocol that facilitates the cross-chain transfer of any data or asset types, not just tokens, thereby making a wide range of blockchains interoperable with each other.`,
        `This interoperability seeks to establish a fully decentralized and private web, controlled by its users, and simplify the creation of new applications, institutions and services.`,
        `The Polkadot protocol connects public and private chains, permissionless networks, oracles and future technologies, allowing these independent blockchains to trustlessly share information and transactions through the Polkadot relay chain (explained further down).`,
        `Polkadot’s native DOT token serves three clear purposes: providing network governance and operations, and creating parachains (parallel chains) by bonding.`,
      ],
      zh: [
        `波卡Polkadot为全球知名区块链跨链项目，由以太坊联合创始人、以太坊黄皮书作者Gavin Wood创建，旨在解决不同区块链之间存在的通信和数据传输障碍问题，曾被彭博社评为“2019年决定数字货币发展方向的4大项目”之一。`,
      ],
    },
    website: "https://polkadot.network/",
    issue: "2017/10/27",
    total: "1059062948",
    circulation: "923049810",
  },
  DOGE: {
    name: "Dogecoin",
    explorer: "https://dogechain.info/chain/Dogecoin",
    intro: {
      en: [
        `Dogecoin (DOGE) is based on the popular "doge" Internet meme and features a Shiba Inu on its logo. The open-source digital currency was created by Billy Markus from Portland, Oregon and Jackson Palmer from Sydney, Australia, and was forked from Litecoin in December 2013. Dogecoin's creators envisaged it as a fun, light-hearted cryptocurrency that would have greater appeal beyond the core Bitcoin audience, since it was based on a dog meme. Tesla CEO Elon Musk posted several tweets on social media that Dogecoin is his favorite coin.`,
      ],
      zh: [
        `狗狗币（DOGE）的名称源于网上超火的表情包"doge“，它的logo上有一只柴犬。这一开源型数字货币由美国俄勒冈州波特兰市的比利·马库斯(Billy Markus)和澳大利亚悉尼市的杰克逊·帕尔默(Jackson Palmer)共同创造，并在2013年12月由莱特币中派生出来。狗狗币的创始人们将其设定为一种轻松有趣的虚拟货币，希望它能吸引比特币核心受众之外的更多用户。Telsa公司的CEO埃隆·马斯克曾数次发推说狗狗币是他的最爱。`,
        `狗狗币主要被用于在Reddit和Twitter上打赏有创意、高质量的内容。`,
      ],
    },
    website: "https://dogecoin.com/",
    issue: "2013/12/12",
    total: "121162098417",
    circulation: "121162098417",
  },
  WGT: {
    name: "W3cGroup Token",
    explorer: "https://w3c.group/wgt",
    intro: {
      en: [
        `WGT is the governance token of the platform Web3.0 Collaborative Group, a blockchain-driven collaborative community for creators  `,
      ],
      zh: [
        `W3 协作组（Web3.0 Collaborative Group）是区块链驱动的创造者协作社区，是基于 Mixin Network 开发的区块链应用。`,
        `WGT是W3 协作组的通证。平台通证 WGT 需通过对社区做出贡献以获得积分，再通过持有的积分挖出。平台通过提供WGT 和其他价值币交易对的流动性，通过自动做市的方式，让挖得的 WGT能够随时轻松出售。`,
      ],
    },
    website: "https://w3c.group",
    issue: "2019/9/11",
    total: "12000000",
    circulation: "",
  },
  BNB: {
    name: "Binance Coin",
    explorer: "https://explorer.binance.org/",
    intro: {
      en: [
        `BNB was launched through an initial coin offering in 2017, 11 days before the Binance cryptocurrency exchange went online. It was originally issued as an ERC-20 token running on the Ethereum network, with a total supply capped at 200 million coins, and 100 million BNBs offered in the ICO. However, the ERC-20 BNB coins were swapped with BEP2 BNB on a 1:1 ratio in April 2019 with the launch of the Binance Chain mainnet, and are now no longer hosted on Ethereum.`,
        `BNB can be used as a payment method, a utility token to pay for fees on the Binance exchange and for participation in token sales on the Binance launchpad. BNB also powers the Binance DEX (decentralized exchange).`,
      ],
      zh: [
        `2017年，币安币通过首次代币发行(ICO)发布，11天后，币安交易所上线。它原本是部署在以太坊网络上的ERC-20代币，总量为2亿枚，其中1亿枚用于ICO。然而，随着币安链主网发布，ERC-20 币安币于2019年4月以1：1的比例与BEP2 币安币交换，不再托管在以太坊上。`,
        `BNB是一种实用令牌，可用作支付手段，您可以用它抵扣在币安交易所的手续费，也可以用它参与币安LaunchPad（代币发行平台）上的令牌销售活动。另外， BNB还为币安DEX（去中心化交易所）提供动力。`,
      ],
    },
    website: "https://www.binance.com",
    issue: "2017/07",
    total: "170532785",
    circulation: "154532785",
  },
  CNB: {
    name: "Cuiniubi",
    explorer: "",
    intro: {
      en: [],
      zh: [],
    },
    website: "",
    issue: "",
    total: "",
    circulation: "",
  },
  UQn: {
    name: "Uqinzen",
    explorer:
      "https://etherscan.io/token/0xac298353ab790e668986ac9e2d3a9ddfc600ff78",
    intro: {
      en: [
        `UQn is a social Token for poetry and literary creators and lovers.`,
      ],
      zh: [`UQn 是一个面向诗歌及文艺创作者、爱好者的社交 Token。`],
    },
    website: "https://uqn.life",
    issue: "2017/12/22",
    total: "321000000",
    circulation: "321000000",
  },
  TSR: {
    name: "TESRA SUPERNET",
    explorer:
      "https://cn.etherscan.com/token/0x58959e0c71080434f237bd42d07cd84b74cef438",
    intro: {
      en: [],
      zh: [
        `TESRA SUPERNET是一个社区化的共享计算网络，基于链下的计算证明，通过扩展链上共识形成去中心化的调度系统和计算网络，结合人工智能与物联网，为未来开放商业体系构建计算价值层。`,
        `TESRA SUPERNET立志于成为一个全球化、可无限扩展的超级计算网络，聚集全球区块链开发者和爱好者共同建设开放型社区，鼓励参与者的自由创新、协作和价值创造，提倡数据隐私安全，构建未来全面可编程社会的计算智能。`,
      ],
    },
    website: "https://tesra.io/en/",
    issue: "2018/10/06",
    total: "10000000000",
    circulation: "",
  },
  SOL: {
    name: "Solana",
    explorer: "https://solanabeach.io/",
    intro: {
      en: [],
      zh: [
        `Solana由高通、英特尔和Dropbox的前工程师于2017年底创立，是一个单链委托权益证明协议，其重点是在不牺牲去中心化或安全的情况下提供可扩展性。`,
        `Solana可扩展解决方案的核心是一个名为历史证明 (PoH)的去中心化时钟，它的建立是为了解决分布式网络中没有单一可信的时间来源的时间问题。通过使用可验证的延迟函数，PoH允许每个节点通过SHA256计算在本地生成时间戳。这样就不需要在整个网络中广播时间戳，从而提高了整个网络的效率。 Solana的使命是支持所有高增长和高频区块链应用，并民主化世界金融系统。`,
      ],
    },
    website: "https://solana.com/",
    issue: "2020",
    total: "494519162",
    circulation: "272637427.58",
  },
  AMITUO: {
    name: "AMITUO",
    explorer:
      "https://mixin.one/snapshots/bdec3118-656a-3ec7-a397-6e2637a1d7bf",
    intro: {
      en: [],
      zh: [
        `阿弥陀佛（梵语Amitābha），又名无量佛、无量光佛、无量寿佛等。`,
        `大乘经载，阿弥陀佛在过去久远劫时曾立大愿，建立西方净土，广渡无边众生，成就无量庄严功德，为大乘佛教所广为崇敬和弘扬。大乘佛经主要如《佛说大乘无量寿庄严清静平等觉经》、《阿弥陀经》、《观无量寿佛经》，对阿弥陀佛及其西方极乐世界均有详述。`,
        `大乘佛教流传之地，如中国、日本等大乘教区，阿弥陀佛信仰也尤为繁盛和重要。而汉传佛教的净土宗，则完全以念佛往生阿弥陀佛的西方净土作为专修的法门。`,
      ],
    },
    website: "https://w3c.group/c/1620796345575579",
    issue: "2010/04/30",
    total: "362880000000000000000000000",
    circulation: "362880000000000000000000000",
  },
};

export default data;
